### ISSUE TITLE
Translation is buggy, translated text will revert back to english after scrolling 2 tabs to the right

### ISSUE THREAD

**Issue by imny94** [JulianJason/The-Travelling-Man#3]
Most probably caused by the reloading of the file and all after moving 2 tabs away. Take a look at locale to help store the previous state.

**Comment by JulianJason** [comment]
Hey take a look at [this](https://developer.android.com/guide/topics/resources/localization.html)

The gist of it is instead of making a huge strings.xml file, we seperate them and selectively load the correct strings.xml with the correct language.
That means we might need an overhaul on the strings.xml file

**Comment by JulianJason** [comment]
I faced a problem with dynamically reloading resources.
The problem was that the activity requires a restart when a locale has been changed since it is referring to a different resource file.

If there was a way to suppress activity change animation or dynamically reload resource file then this would be solved.

I pushed it to another branch so check it out

**Comment by imny94** [comment]
Localised and fixed :)
